<a target="_blank" href="https://colab.research.google.com/github/ashkan-mokarian/d2l-pytorch/blob/main/chapter_builder_guide/1_io.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [1]:
import torch

In [2]:
x = torch.arange(4)
torch.save(x, 'x-file')

In [3]:
x2 = torch.load('x-file')
print(x2)

tensor([0, 1, 2, 3])


In [4]:
my_dict = {'x': torch.zeros(3,5), 'y': torch.ones(5)}
torch.save(my_dict, 'dict-file')
loaded_dict = torch.load('dict-file')
print(loaded_dict)

{'x': tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]), 'y': tensor([1., 1., 1., 1., 1.])}


In [5]:
from torch import nn
from torch.nn import functional as F

In [6]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.LazyLinear(256)
        self.out = nn.LazyLinear(10)
    
    def forward(self, X):
        return self.out(F.relu(self.hidden(X)))

In [9]:
model = MLP()
X = torch.randn((3, 10))
y_orig = model(X)
print(y_orig)

torch.save(model.state_dict(), 'model.dict')

tensor([[ 0.3620, -0.5910,  0.0919, -0.0287,  0.2053,  0.2669,  0.3183, -0.0139,
         -0.0164, -0.5032],
        [ 0.1654, -0.1625, -0.0626,  0.0124,  0.1308,  0.2323,  0.0149,  0.2468,
          0.0492, -0.1549],
        [ 0.2316, -0.2959, -0.1268, -0.1075, -0.3235,  0.1609, -0.0161, -0.2080,
         -0.2984, -0.3073]], grad_fn=<AddmmBackward0>)


In [12]:
clone = MLP()
clone.load_state_dict(torch.load('model.dict'))
print(clone)
clone.eval()
print(clone)
y_clone = clone(X)
y_clone == y_orig

MLP(
  (hidden): LazyLinear(in_features=0, out_features=256, bias=True)
  (out): LazyLinear(in_features=0, out_features=10, bias=True)
)
MLP(
  (hidden): LazyLinear(in_features=0, out_features=256, bias=True)
  (out): LazyLinear(in_features=0, out_features=10, bias=True)
)


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])